plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
    id 'com.diffplug.eclipse.apt' version '3.23.0'
    id 'org.spongepowered.mixin' version '0.7.+'
}

group = "com.${gradle.ext.modID}"

base {
    archivesName = "${gradle.ext.modName} ${gradle.ext.modVersion} for ${gradle.ext.minecraftVersion}"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

println "Java: ${System.getProperty 'java.version'}, JVM: ${System.getProperty 'java.vm.version'} (${System.getProperty 'java.vendor'}), Arch: ${System.getProperty 'os.arch'}"
println "Minecraft: ${gradle.ext.minecraftVersion}"
println "Forge: ${gradle.ext.forgeVersion}"
println "${gradle.ext.modName}: ${gradle.ext.modVersion}"

minecraft {
    mappings channel: 'official', version: "${gradle.ext.minecraftVersion}"
    copyIdeResources = true
    accessTransformer = file('src/main/resources/META-INF/accesstransformer.cfg')

    runs {
        configureEach {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.console.level', 'debug'

            mods {
                "${gradle.ext.modID}" {
                    source sourceSets.main
                }
            }
        }

        client {
            property 'forge.enabledGameTestNamespaces', "${gradle.ext.modID}"
        }

        server {
            property 'forge.enabledGameTestNamespaces', "${gradle.ext.modID}"
        }

        gameTestServer {
            property 'forge.enabledGameTestNamespaces', "${gradle.ext.modID}"
        }

        data {
            args '--mod', "${gradle.ext.modID}", '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')
        }
    }
}

sourceSets.main.resources { 
    srcDir 'src/generated/resources' 
}

dependencies {
    minecraft "net.minecraftforge:forge:${gradle.ext.minecraftVersion}-${gradle.ext.forgeVersion}"
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
}

mixin {
	add sourceSets.main, "${gradle.ext.modID}.mixins.refmap.json"
	config "${gradle.ext.modID}.mixins.json"
	debug.verbose = true
	debug.export = true
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes([
            "Specification-Title": "${gradle.ext.modName}",
            "Specification-Vendor": "${gradle.ext.modID}mod",
            "Specification-Version": "1",
            "Implementation-Title": project.name,
            "Implementation-Version":"${gradle.ext.modVersion}",
            "Implementation-Vendor" :"${gradle.ext.modID}mod",
            "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
    finalizedBy 'reobfJar'
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/mcmodsrepo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
