modLoader="javafml"
loaderVersion="[44,)"
logoFile="raremoon.png"
license="All Rights Reserved"

[[mods]]
    displayName="RareMoon"
    version="1.0.0"
    modId="raremoon"
    credits="NecroticPlague - collaboration/testing"
    authors="burnsqc"
    description='''RareMoon is a mod for Minecraft that occasionally causes a rare moon type to appear, affecting gameplay for the night.'''

[[dependencies.raremoon]] 
    modId="forge" 
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.raremoon]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3]"
    ordering="NONE"
    side="BOTH"